package org.nuclearmasses.gui.util;

import java.awt.*;
import javax.swing.JFrame;
import java.awt.geom.AffineTransform;

/**
 * This class creates customized 1-D plots.
 */
public class StaticPlotter extends JFrame {

	// Conversion factor from ln to log_10

	/** The Constant log10. */
	public static final double log10 = 0.434294482;  // Base-10 log of e

	/** The g2. */
	Graphics2D g2;

	/** The y. */
	public double x[][],y[][];

	// --------------------------- METHOD plotIt ---------------------------------
	// Method plotIt to draw x-y plot for arbitrary number of curves in
	// linear-linear, log-linear, or log-log form.  Set up to
	// to be called from another graphics object, permitting a plot to be
	// inserted on an arbitrary part of the canvas.  (Thus the user
	// is responsible to be certain that the calling graphics object does
	// not erase the plot generated by this method with its own repaints.) Data
	// are passed to the method as arrays, as are many parameters that give
	// detailed control over the look of the resulting plot.  The user must
	// set up the parameters and the data arrays to be passed from the program
	// invoking the method; an example is given below.  PlotIt assumes data
	// equally spaced in the x coordinate. PlotIt will work with either
	// standalone applications or applets.
	//
	// (See the programs plotItTest.java and ggtest.java in this directory
	// for examples of using plotIt in an application and an applet respectively.)
	//
	//     USAGE:
	//
	//     The invocation of the GraphicsGoodies2.plotIt(...) method
	//     will generally be in a paint method of say a JPanel or
	//     Applet object, as illustrated below.  First instantiate
	//     the GraphicsGoodies2 class and then use the instance to
	//     invoke the plotIt method from within the paint method:
	//
	//    GraphicsGoodies2 gg = new GraphicsGoodies2();  // Instantiate
	//
	//    public void paint(Graphics g){
	//
	//        // invoke the GraphicsGoodies2.plotIt method
	//
	//        gg.plotIt(plotmode,x1,y1,x2,y2,kmax,imax,mode,
	//                  xlegoff,ylegoff,xdplace,ydplace,
	//                  npoints,doscalex,doscaley,doplot,xmin,xmax,ymin,ymax,
	//                  delxmin,delxmax,delymin,delymax,
	//                  lcolor,x,y,bgcolor,axiscolor,legendfg,framefg,
	//                  dropShadow,legendbg,labelcolor,ticLabelColor,
	//                  xtitle,ytitle,curvetitle,logStyle, ytickIntervals,
	//                  xtickIntervals, showLegend, g);
	//     }
	//
	//     Where: Graphics g - The graphics object from which this method is being
	//            called.  Other parameters are described below.
	//
	//
	//  LIST OF PARAMETERS THAT CAN BE SET WITH EXAMPLE VALUES AND DESCRIPTION:
	//
	//    int plotmode=1;       // Type of plot: 0=linear, 1=log-lin (x axis lin), 2=log-log, 3=lin-log (y axis lin)
	//
	//    // Set the coordinates (relative to the graphics container
	//    // from which the method is being invoked) for the plot
	//    // window. Coordinates in pixels measured from the upper
	//    // left corner of the container (e.g., a frame or an applet window).
	//
	//    int x1=5;             // x coordinate of upper left corner of plot
	//    int y1=5;             // y coordinate of upper left corner of plot
	//    int x2=215;           // x coordinate of lower right corner of plot
	//    int y2=265;           // y coordinate of lower right corner of plot
	//
	//    int kmax=200;         // Max number of points for each curve. Must
	//                          // be as large as largest entry in npoints[].
	//    int imax=2;           // Max number of separate curves
	//
	//    int mode[]={6,2};     // array giving display mode for curve
	//                          // with 1=solid line, 2=lines+dots, 3=dashed line,
	//                          // 4=open circles, 5=filled circles, 6=filled squares,
	//                          // 7=open squares, 8=x, 9=x+square, 10=+, 11=+ and square,
	//                          // 12=open diamonds, 13=open down triangle,
	//                          // 14=open up triangle, 15=horizontal open oval,
	//                          // 16=horizontal filled oval, 17=vertical open oval,
	//                          // 18=vertical filled oval.
	//                          // If mode other than line mode, dotSize below sets
	//                          // the size of the plotting symbol.
	//
	//    int dotSize = 3;      // If plotting dots or symbols, width of dot
	//                          // in pixels.  Minimum size is 3 pixels.
	//                          // Smaller sizes will be reset to 3 pixels.
	//
	//    // Offset of legend box from upper left corner of plot:
	//
	//    int xlegoff=100;      // x offset in pixels from upper left of frame
	//    int ylegoff=10;       // y offset in pixels from upper left of frame
	//
	//    int xdplace=0;        // Number decimal places for numbers on x axis
	//    int ydplace=0;        // Number decimal places for numbers on y axis
	//
	//    int npoints[]={20,100};  // vector giving number of data points for curve
	//                             // i with i=0,1, ... imax.  Entries less than
	//                             // or equal to kmax.  Rule of thumb: if display
	//                             // mode is lines (mode[i]=2), npoints[i] should be
	//                             // about 1/2 the graph width in pixels.  If mode
	//                             // is dots (e.g., mode[i]=1), npoints[i] should be
	//                             // about 10-15% of graph width in pixels.  If
	//                             // display mode is dashed line (mode[i]=7),
	//                             // npoints[i] should be about 1/2-3/4 graph width.
	//
	//    int doscalex=0;   // 1 -> scale min & max of x by data; 0 -> no autoscale
	//    int doscaley=0;   // 1 -> scale min & max of y by data; 0 -> no autoscale
	//
	//    int doplot[] = {1,1};    // Vector controlling whether curve
	//                             // i=0,1,2,...imax is plotted: plot=1; noplot=0
	//                             // (Reset to toggle curve visibility)
	//
	//    // Following overridden by autoscaling if doscalex=1 or doscaley=1
	//
	//    double xmin=0;           // Min plot x if doscalex=0
	//    double xmax=10.0;        // Max plot x if doscalex=0
	//    double ymin=1.0;         // Min plot y if doscaley=0
	//    double ymax=10000.0;     // Max plot y if doscaley=0
	//
	//    // Set the amount of empty space above, below, right, left
	//    // of the plotted data as a fraction of the total width of
	//    // the plot area.  For example, delymax=0.10 leaves 10%
	//    // empty space above the highest data point
	//
	//    double delxmin=0.0;      // fraction space left on left
	//    double delxmax=0.0;      // fraction space left on right
	//    double delymin=0.0;      // fraction space left below
	//    double delymax=0.0;      // fraction space left above
	//
	//    // Set the colors for the lines and symbols for the curves
	//
	//    Color lcolor[]={AIorange,AIpurple};       // imax entries
	//
	//    // Set the colors for the plot background, labels, & axes,
	//    // and legend box
	//
	//    Color bgcolor=gray250;            // plot background color
	//    Color axiscolor=gray51;           // axis color
	//    Color legendfg=Color.white;       // legend box color
	//    Color framefg=gray204;            // frame color
	//    Color dropShadow = gray153;       // legend box dropshadow color
	//    Color legendbg=gray204;           // legend box frame color
	//    Color labelcolor = gray51;        // axis label color
	//    Color ticLabelColor = gray51;     // axis tic label color
	//
	//  // Set the strings for labeling the axes and for
	//  // each of the curves in the plot legend
	//
	//    String xtitle="Time (weeks)";     // String for x-axis label
	//    String ytitle="$";                // String for y-axis label
	//    String curvetitle[]={"Salary", "Expenses"};        // imax entries
	//
	//    int logStyle = 0;     // 0 to show number, 1 to show log of number
	//                          // on axis when plot is logarithmic
	//
	//    int ytickIntervals = 4;     // Number of intervals between y ticks
	//    int xtickIntervals = 5;     // Number of intervals between x ticks
	//    boolean showLegend = true;  // Show legend box (true or false)
	//
	//
	//    SUPPLYING DATA TO THE PLOTTING METHOD:
	//
	//    You must supply data to the plotIt method, first by defining
	//    2-dimensional arrays to hold x and y values, and then filling
	//    those arrays with your data.  The following examples illustrate
	//    setting up the arrays and filling them.
	//
	//    // Create the data arrays.  They will be filled in the putData()
	//    // method defined below
	//
	//    double x[][]=new double[imax][kmax];  // data array for x coordinates
	//    double y[][]=new double[imax][kmax];  // data array for y coordinates
	//                                          // Form: x[i][k] and y[i][k], with
	//                                // i=0,1, ... imax = index of separate curves;
	//                                // k=0,1, ... kmax = index of data points
	//
	//
	//    // Sample routine to fill data arrays.  Replace this with a method
	//    // to fill the data arrays with the data you desire to plot.  Be
	//    // certain that the number of points generated is consistent with
	//    // npoints[] defined above.  Also note that PlotIt() expects
	//    // x coordinates of the data set to be equally spaced for best results
	//    // if plotting in the line mode (mode[i]=1).
	//
	//    void putData () {
	//	    // Fill the data array for plot number 1
	//	    for (int k=0; k<npoints[0]; k++){
	//            // First curve
	//	        x[0][k]=((xmax-xmin)/(double)npoints[0])*(double)k;
	//	        y[0][k]=350-2*x[0][k]*x[0][k];
	//            }
	//            // Second curve
	//	    for (int k=0; k<npoints[1]; k++){
	//	        x[1][k]=((xmax-xmin)/(double)npoints[1])*(double)k;
	//	        y[1][k]= 50 + 4.9*x[1][k]*x[1][k];
	//	    }
	//    }
	//
	//   See the programs plotItTest.java and ggtest.java in this directory
	//   for examples of using plotIt in an application and an applet respectively.
	// -------------------------------------------------------------------------

	/**
	 * Creates a plot. The parameters for this method need to be properly documented.
	 *
	 * @param plotmode the plotmode
	 * @param x1 the x1
	 * @param y1 the y1
	 * @param x2 the x2
	 * @param y2 the y2
	 * @param kmax the kmax
	 * @param imax the imax
	 * @param mode the mode
	 * @param dotSize the dot size
	 * @param xlegoff the xlegoff
	 * @param ylegoff the ylegoff
	 * @param xdplace the xdplace
	 * @param ydplace the ydplace
	 * @param npoints the npoints
	 * @param doscalex the doscalex
	 * @param doscaley the doscaley
	 * @param doplot the doplot
	 * @param xxmin the xxmin
	 * @param xxmax the xxmax
	 * @param yymin the yymin
	 * @param yymax the yymax
	 * @param delxmin the delxmin
	 * @param delxmax the delxmax
	 * @param delymin the delymin
	 * @param delymax the delymax
	 * @param lcolor the lcolor
	 * @param bgcolor the bgcolor
	 * @param axiscolor the axiscolor
	 * @param legendfg the legendfg
	 * @param framefg the framefg
	 * @param dropShadow the drop shadow
	 * @param legendbg the legendbg
	 * @param labelcolor the labelcolor
	 * @param ticLabelColor the tic label color
	 * @param xtitle the xtitle
	 * @param ytitle the ytitle
	 * @param curvetitle the curvetitle
	 * @param logStyle the log style
	 * @param ytickIntervals the ytick intervals
	 * @param xtickIntervals the xtick intervals
	 * @param showLegend the show legend
	 * @param xx the xx
	 * @param yy the yy
	 * @param majorX the major x
	 * @param minorX the minor x
	 * @param majorY the major y
	 * @param minorY the minor y
	 * @param title the title
	 * @param subtitle the subtitle
	 * @param titleString the title string
	 * @param subtitleString the subtitle string
	 * @param insideLegend the inside legend
	 * @param location the location
	 * @param xoffset the xoffset
	 * @param yoffset the yoffset
	 * @param topmarg the topmarg
	 * @param rightmarg the rightmarg
	 * @param g the g
	 */
	public void plotIt(int plotmode,int x1,int y1,int x2,int y2,int kmax,
			int imax,int mode[],int dotSize,int xlegoff,
			int ylegoff,int xdplace,int ydplace,
			int npoints[],int doscalex,int doscaley,int doplot[],
			double xxmin,double xxmax,double yymin,double yymax,
			double delxmin,double delxmax,double delymin,double delymax,
			Color lcolor[],Color bgcolor,
			Color axiscolor,Color legendfg,Color framefg,
			Color dropShadow,Color legendbg,Color labelcolor,
			Color ticLabelColor,String xtitle,String ytitle,
			String curvetitle[],int logStyle, int ytickIntervals,
			int xtickIntervals,boolean showLegend,
			double xx[][],double yy[][],boolean majorX, boolean minorX, 
			boolean majorY, boolean minorY, boolean title, boolean subtitle,  
			String titleString, String subtitleString, 
			boolean insideLegend, String location, int xoffset, int yoffset, 
			int topmarg, int rightmarg, Graphics g){

		double xmin, xmax, ymin, ymax;

		Font titleFont = new Font("SanSerif", Font.PLAIN, 13);
		FontMetrics titleFontMetrics = getFontMetrics(titleFont);
		Font mediumFont = new Font("SanSerif", Font.PLAIN, 11);
		FontMetrics mediumFontMetrics = getFontMetrics(mediumFont);
		Font smallFont = new Font("SanSerif", Font.PLAIN, 9);
		FontMetrics smallFontMetrics = getFontMetrics(smallFont);

		try{

			g2 = (Graphics2D)g;

		}catch(Exception e){

			e.printStackTrace();

		}

		// Create memory for data arrays.  First argument is
		// the plot number.  Second argument is the data point
		// number for that plot.

		x=new double[imax][kmax];
		y=new double[imax][kmax];

		double[] logRatio = {0.30103, 0.477121, 0.60206, 0.69897, 0.778151, 0.845098, 0.90309, 0.954243};
		double[] linRatio = {0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9};

		//RESET//VALUES//OF//ARRAYS//FOR//LOG-LOG//LOG-LIN//LIN-LOG//PLOTTING///////////////////////////////
		int i,k;

		for (i=0; i<imax; i++){

			for(k=0; k<npoints[i]; k++){

				switch(plotmode){
				case 0:                 // linear plot
					x[i][k]=xx[i][k];
					y[i][k]=yy[i][k];

					break;

				case 1:                 // log-lin plot
					x[i][k]=xx[i][k];

					// first check whether possible to take Log of y
					// and bail out if there are negative or zero numbers

					if(yy[i][k]<=0.0){
						g2.setFont(titleFont);
						g2.setColor(axiscolor);
						g2.drawString("Data for y zero or negative.",x1+10,y1+20);
						g2.drawString("Can't make Log plot.",x1+10,y1+35);
						g2.drawRect(x1,y1,x2-x1,y2-y1);
						System.out.println
						("y-data zero or negative. No can do Log plot: "
								+"x=" +xx[i][k] + " y="+ yy[i][k] + " i=" + i + " k=" + k);
						return;
					}

					y[i][k]=log10*Math.log(yy[i][k]);

					break;

				case 2:                 // log-log plot
					// first check whether possible to take Log of x & y
					// and bail out if there are negative or zero numbers

					if(yy[i][k]<=0.0 || xx[i][k]<= 0.0){
						g2.setFont(titleFont);
						g2.setColor(axiscolor);
						g2.drawString("Data values zero or negative.",x1+10,y1+20);
						g2.drawString("Can't make Log-Log plot.",x1+10,y1+35);
						g2.drawRect(x1,y1,x2-x1,y2-y1);

						System.out.println
						("Data zero or negative. No can do Log-Log plot: "
								+"x=" +xx[i][k] + " y="+ yy[i][k] + " i=" + i + " k=" + k);



						return;
					}
					x[i][k]=log10*Math.log(xx[i][k]);
					y[i][k]=log10*Math.log(yy[i][k]);
					break;

				case 3:                 // lin-log plot
					// first check whether possible to take Log of x
					// and bail out if there are negative or zero numbers

					if(xx[i][k]<=0.0){
						g2.setFont(titleFont);
						g2.setColor(axiscolor);
						g2.drawString("Data values zero or negative.",x1+10,y1+20);
						g2.drawString("Can't make Lin-Log plot.",x1+10,y1+35);
						g2.drawRect(x1,y1,x2-x1,y2-y1);

						System.out.println
						("Data zero or negative. No can do Log-Log plot: "
								+"x=" +xx[i][k] + " y="+ yy[i][k] + " i=" + i + " k=" + k);



						return;
					}

					x[i][k]=log10*Math.log(xx[i][k]);
					y[i][k]=yy[i][k];
					break;
				}
			}
		}

		// Reset min and max values to their base-10 logs if log modes
		if(plotmode == 1 || plotmode == 2) {
			yymin = log10*Math.log(yymin);
			yymax = log10*Math.log(yymax);
		}
		if(plotmode == 2) {
			xxmin = log10*Math.log(xxmin);
			xxmax = log10*Math.log(xxmax);
		}
		if(plotmode == 3) {
			xxmin = log10*Math.log(xxmin);
			xxmax = log10*Math.log(xxmax);
		}
		// find mimima and maxima in data set
		if(doscalex==0){ 

			// set default min & max values for x
			xmin=xxmin;
			xmax=xxmax;
		}
		else{
			xmin=x[0][0];
			xmax=x[0][0];
			for (i=0; i<imax; i++){
				for(k=0; k<npoints[i]; k++){
					if(x[i][k] < xmin){xmin=x[i][k];}
					if(x[i][k] > xmax){xmax=x[i][k];}
				}
			}
		}

		if(doscaley==0){           // set default min & max values for y
			ymin=yymin;
			ymax=yymax;
		}
		else{
			ymin=y[0][0];
			ymax=y[0][0];
			for (i=0; i<imax; i++){
				for(k=0; k<npoints[i]; k++){
					if(y[i][k] < ymin){ymin=y[i][k];}
					if(y[i][k] > ymax){ymax=y[i][k];}
				}
			}
		}

		// Set the amount of empty space above, below, right, left
		// of the plotted data
		ymin=ymin-delymin*Math.abs(ymax-ymin);
		ymax=ymax+delymax*Math.abs(ymax-ymin);
		xmin=xmin-delxmin*Math.abs(xmax-xmin);
		xmax=xmax+delxmax*Math.abs(xmax-xmin);

		// Set some sizes
		int psize=Math.max(3,dotSize);    // point symbol size;
		// must be integer >= 3
		int hpsize=psize/2;
		int wid=x2-x1;          // width of plot in pixels
		int hite=y2-y1;         // height of plot in pixels

		double xscale,yscale;

		// set scaling factors for x,y -> pixels
		xscale=1.0*(wid-xoffset-rightmarg)/(Math.abs(xmax-xmin));
		yscale=1.0*(hite-yoffset-topmarg)/(ymax-ymin);
		double ticspace=(xscale*Math.abs(xmax-xmin)/xtickIntervals);
		double tmark;
		int fshift, vshift;
		g2.setFont(mediumFont);

		// draw plot rectangle
		g2.setColor(bgcolor);
		g2.fillRect(x1,y1,wid,hite);
		g2.setColor(framefg);
		g2.drawRect(x1,y1,wid,hite);
		g2.setColor(axiscolor);

		//MAJOR//TEMP//GRIDLINES///////////////////////////////////////////////////////////////////
		g2.setColor(Color.lightGray);
		if(majorX){

			for(k=1; k<=xtickIntervals-1; k++){

				boolean drawXMajorGrid = false;
				tmark=(k*ticspace)/xscale+xmin;

				if(xtickIntervals<=25){
					drawXMajorGrid = true;
				}else if(xtickIntervals>25 && xtickIntervals<=100){
					if(Math.round(tmark)%5==0){
						drawXMajorGrid = true;
					}
				}else if(xtickIntervals>100 && xtickIntervals<=150){
					if(Math.round(tmark)%10==0){
						drawXMajorGrid = true;
					}
				}else{
					if(Math.round(tmark)%20==0){
						drawXMajorGrid = true;
					}
				}

				if(drawXMajorGrid){
					g2.drawLine(x1+xoffset+(int)(k*ticspace), y2-yoffset,
							x1+xoffset+(int)(k*ticspace), y1+topmarg);
				}
			}
		}

		//MINOR//TEMP//GRIDLINES///////////////////////////////////////////////////////////////////
		if(plotmode==2 || plotmode==3){
			if(minorX){
				for(k=0; k<=xtickIntervals-1; k++){
					for(int j=0; j<8; j++){
						g2.drawLine(x1+xoffset+(int)((k+logRatio[j])*ticspace) , y2-yoffset,
								x1+xoffset+(int)((k+logRatio[j])*ticspace), y1+topmarg);
					}
				}
			}
		}else if(plotmode==1 || plotmode==0){

			if(minorX){
				for(k=0; k<=xtickIntervals-1; k++){
					g2.drawLine(x1+xoffset+(int)(k*ticspace), y2-yoffset,
							x1+xoffset+(int)(k*ticspace), y1+topmarg);
				}
			}
		}
		//DRAW//X-AXIS//FOR//PLOT////////////////////////////////////////////////////////////////////
		g2.setColor(axiscolor);

		g2.drawLine(x1+xoffset,y2-yoffset,x1+wid-rightmarg,y2-yoffset);//x-axis
		g2.drawLine(x1+xoffset,y1+topmarg,x1+wid-rightmarg,y1+topmarg);//top x-axis

		//TIC//MARKS//FOR//X-AXIS//////////////////////////////////////////////////////////////////
		for (k=0; k<=xtickIntervals; k++){

			// Tic marks
			g2.setColor(axiscolor);
			tmark=(k*ticspace)/xscale+xmin;

			boolean drawXTick = false;

			if(xtickIntervals<=25){
				drawXTick = true;
			}else if(xtickIntervals>25 && xtickIntervals<=100){
				if(Math.round(tmark)%5==0){
					drawXTick = true;
				}
			}else if(xtickIntervals>100 && xtickIntervals<=150){
				if(Math.round(tmark)%10==0){
					drawXTick = true;
				}
			}else{
				if(Math.round(tmark)%20==0){
					drawXTick = true;
				}
			}

			if(drawXTick){
				g2.drawLine(x1+xoffset+(int)(k*ticspace), y2-yoffset,
						x1+xoffset+(int)(k*ticspace), y2-yoffset-5);
			}

			// Labels for ticmarks
			g2.setColor(ticLabelColor);
					fshift=mediumFontMetrics.stringWidth(this.decimalPlace(xdplace, Math.round(tmark)))/2;

					if(plotmode<2){    //  If not log-log

						boolean drawXLabel = false;

						if(xtickIntervals<=25){
							drawXLabel = true;
						}else if(xtickIntervals>25 && xtickIntervals<=100){
							if(Math.round(tmark)%5==0){
								drawXLabel = true;
							}
						}else if(xtickIntervals>100 && xtickIntervals<=150){
							if(Math.round(tmark)%10==0){
								drawXLabel = true;
							}
						}else{
							if(Math.round(tmark)%20==0){
								drawXLabel = true;
							}
						}

						if(drawXLabel){
							g2.drawString(this.decimalPlace(xdplace,tmark), x1+xoffset+(int)(k*ticspace)-fshift, y2-yoffset+15);
						}

					}else{             //  For log-log case

						// Decide whether to display number or log
						if (logStyle == 0 && plotmode == 2) {
							tmark = Math.pow(10,tmark);
						}


						String base = "10";

						int al = 0;

						if(Double.valueOf(this.decimalPlace(xdplace, tmark)).doubleValue()<1e-10 
								&& Double.valueOf(this.decimalPlace(xdplace, tmark)).doubleValue()>0){

							fshift=mediumFontMetrics.stringWidth(this.decimalPlace(xdplace,tmark))/2;

							al = rightSuperScript(base, "0", x1+xoffset+(int)(k*ticspace)
									-fshift, y2-yoffset+15, mediumFont, "large", g2);			

						}else{

							if(Double.valueOf(this.decimalPlace(xdplace,tmark)).doubleValue()>0.5 
									|| Double.valueOf(this.decimalPlace(xdplace,tmark)).doubleValue()<-0.5){

								fshift=smallFontMetrics.stringWidth(this.decimalPlace(xdplace,tmark));

								al = rightSuperScript(base, this.decimalPlace(xdplace,tmark), x1+xoffset+(int)(k*ticspace)
										-fshift, y2-yoffset+15, mediumFont, "large", g2);

							}else{

								fshift=smallFontMetrics.stringWidth("0");

								al = rightSuperScript(base, "0", x1+xoffset+(int)(k*ticspace)
										-fshift, y2-yoffset+15, mediumFont, "large", g2);

							}
						}	 
					}
		}

		//TIC//MARKS//FOR//Y-AXIS////////////////////////////////////////////////////////////////////
		ticspace=(yscale*Math.abs(ymax-ymin)/ytickIntervals);
		g2.setFont(smallFont);
		g2.setColor(Color.lightGray);

		//MAJOR//RATE//GRIDLINES///////////////////////////////////////////////////////////////////////
		if(majorY){

			for(k=1; k<=ytickIntervals-1; k++){

				boolean drawYMajorGrid = false;
				tmark=(k*ticspace)/yscale+ymin;

				if(ytickIntervals<=20){
					drawYMajorGrid = true;
				}else if(ytickIntervals>20){
					if(Math.round(tmark)%5==0){
						drawYMajorGrid = true;
					}
				}

				if(drawYMajorGrid){
					g2.drawLine(x1+xoffset, y2-yoffset-(int)(k*ticspace),
							x1+wid-rightmarg, y2-yoffset-(int)(k*ticspace));
				}

			}
		}

		//MINOR//RATE//GRIDLINES//////////////////////////////////////////////////////////////////////////////

		if(plotmode==3 || plotmode==0){

			if(minorY){
				for(k=0; k<=ytickIntervals-1; k++){
					for(int j=0; j<9; j++){
						g2.drawLine(x1+xoffset, y2-yoffset-(int)((k+linRatio[j])*ticspace),
								x1+wid-rightmarg, y2-yoffset-(int)((k+linRatio[j])*ticspace));
					}
				}
			}

		}else{

			if(minorY){
				for(k=0; k<=ytickIntervals-1; k++){
					g2.drawLine(x1+xoffset, y2-yoffset-(int)(k*ticspace),
							x1+wid-rightmarg, y2-yoffset-(int)(k*ticspace)); 
				}
			}
		}

		//DRAW//Y-AXIS//FOR//PLOT//////////////////////////////////////////////////////////////////////
		g2.setColor(axiscolor);

		g2.drawLine(x1+xoffset,y2-yoffset,x1+xoffset,y1+topmarg);//y-axis
		g2.drawLine(x1+wid-rightmarg,y2-yoffset,x1+wid-rightmarg,y1+topmarg);//right y-axis

		//Draw ALL ticks
		for(k=0; k<=ytickIntervals; k++){


			boolean drawYTick = false;
			tmark=(k*ticspace)/yscale+ymin;

			if(ytickIntervals<=20){
				drawYTick = true;
			}else if(ytickIntervals>20){
				if(Math.round(tmark)%5==0){
					drawYTick = true;
				}
			}

			if(drawYTick){
				g2.setColor(Color.black);
				g2.drawLine(x1+xoffset, y2-yoffset-(int)(k*ticspace),
						x1+xoffset+5, y2-yoffset-(int)(k*ticspace));

				//tick marks right y-axis
				g2.drawLine(x1+wid-rightmarg, y2-yoffset-(int)(k*ticspace),
						x1+wid-rightmarg-5, y2-yoffset-(int)(k*ticspace));
			}

		}

		//JLabel even tickMarks
		for (k=0; k<=ytickIntervals; k++){

			// Labels for tic marks
			g2.setColor(ticLabelColor);
			tmark=(k*ticspace)/yscale;
			vshift=smallFont.getSize()/2;
			double yvalue = ymin + k*Math.abs(ymax-ymin)/ytickIntervals;

			// If log plot, decide whether to display number or log
			if (logStyle == 0 && plotmode >= 1 && plotmode<3) {
				yvalue = Math.pow(10,yvalue);
			}



			if(Double.valueOf(this.decimalPlace(ydplace, yvalue)).doubleValue()<1e-5 
					&& Double.valueOf(this.decimalPlace(ydplace, yvalue)).doubleValue()>0){

				String base = "10";

				fshift=smallFontMetrics.stringWidth("0");

				int al = rightSuperScript(base, "0", x1+xoffset-fshift-15,
						y2-yoffset-(int)(k*ticspace)+vshift, mediumFont, "large", g2);

			}else{

				if(plotmode >= 1 && plotmode<3){

					String base = "10";

					if(Double.valueOf(this.decimalPlace(ydplace,yvalue)).doubleValue()>0.5 
							|| Double.valueOf(this.decimalPlace(ydplace,yvalue)).doubleValue()<-0.5){

						fshift=smallFontMetrics.stringWidth(this.decimalPlace(ydplace,yvalue));

						int al = rightSuperScript(base, this.decimalPlace(ydplace,yvalue), x1+xoffset-fshift-15,
								y2-yoffset-(int)(k*ticspace)+vshift, mediumFont, "large", g2);

					}else{

						fshift=smallFontMetrics.stringWidth("0");

						int al = rightSuperScript(base, "0", x1+xoffset-fshift-15,
								y2-yoffset-(int)(k*ticspace)+vshift, mediumFont, "large", g2);

					}

				}else{
					g2.setFont(mediumFont);
					
					boolean drawYLabel = false;
					tmark=(k*ticspace)/yscale+ymin;

					if(ytickIntervals<=20){
						drawYLabel = true;
					}else if(ytickIntervals>20){
						if(Math.round(tmark)%5==0){
							drawYLabel = true;
						}
					}

					if(drawYLabel){
					
						fshift=smallFontMetrics.stringWidth(this.decimalPlace(ydplace,yvalue));
	
						g2.drawString(this.decimalPlace(ydplace,yvalue),
								x1+xoffset-fshift-5,
								y2-yoffset-(int)(k*ticspace)+vshift);

					}
					

				}
			}      

		}

		//  JLabel for x-axis
		g2.setFont(titleFont);
		g2.setColor(labelcolor);

		if(plotmode==2 && logStyle == 1){
			xtitle= xtitle;   
		}

		int shift=titleFontMetrics.stringWidth(xtitle)/2;

		int d = (int)((x2-rightmarg-x1-xoffset-2.0*shift)/2.0);

		g2.drawString(xtitle, d+x1+xoffset, y2-8);

		//LABEL//FOR//Y-AXIS/////////////////////////////////////////////////////////////////////////
		if(plotmode>0 && logStyle == 1){
			ytitle=ytitle;
		}




		shift=titleFontMetrics.stringWidth(ytitle)/2;
		d = (y2-yoffset) - (y1+topmarg);
		int D = (int)(d/2.0)+shift;

		g2.translate(x1+xoffset, y1+topmarg);

		g2.transform(AffineTransform.getRotateInstance(-Math.PI/2));

		g2.drawString(ytitle, -D, -(x1+xoffset) + 25);

		g2.transform(AffineTransform.getRotateInstance(Math.PI/2));

		g2.translate(-x1-xoffset, -y1-topmarg);



		//DRAW//TITLES////////////////////////////////////////////////////////////////////////////////

		shift=titleFontMetrics.stringWidth(titleString)/2;

		d = (int)((x2-rightmarg-x1-xoffset-2.0*shift)/2.0);

		g2.drawString(titleString, d+x1+xoffset, y1 + 20);

		int colorIndex = 0;

		//PLOT//THE//GRAPHS/////////////////////////////////////////////////////////////////////
		int xk, yk, xprev, yprev;
		for(i=0; i<imax; i++){
			boolean go = false;
			boolean first = false;
			int kindex = 0;

			colorIndex = i;

			if(doplot[i]==1){

				/*if(i>=40){

               	  	colorIndex=i-40;

               	  }*/

				g2.setColor(lcolor[colorIndex]);

				switch(mode[i])
				{

				case 1:                     // If solid line plot

					g2.setStroke(new BasicStroke(1));

					xk=(int)((x[i][0]-xmin)*xscale);
					yk=(int)((y[i][0]-ymin)*yscale);
					for(k=0; k<npoints[i]; k++) {

						xprev=xk;
						yprev=yk;

						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){  



						}else{
							go = true;
							if(!first){
								xk=(int)((x[i][k]-xmin)*xscale);
								yk=(int)((y[i][k]-ymin)*yscale);
								first = true;
							}else{
								if( xprev < 0 || yprev < 0 ){
									//Do nothing
								}else{
									xk=(int)((x[i][k]-xmin)*xscale);
									yk=(int)((y[i][k]-ymin)*yscale);



									g2.drawLine(xprev+xoffset+x1,
											-yprev+y2-yoffset,
											xk+xoffset+x1,
											-yk+y2-yoffset);
								}
							}
						}
					}
					break;

				case 2:                  // If line + point

					xk=(int)((x[i][0]-xmin)*xscale);
					yk=(int)((y[i][0]-ymin)*yscale);
					for(k=0; k<npoints[i]; k++) {

						xprev=xk;
						yprev=yk;

						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){  

						}else{
							go = true;
							if(!first){
								xk=(int)((x[i][k]-xmin)*xscale);
								yk=(int)((y[i][k]-ymin)*yscale);
								g2.fillOval(x1+xoffset+xk-hpsize,
										y2-yk-hpsize-yoffset,
										psize,psize);
								first = true;
							}else{
								if( xprev < 0 || yprev < 0 ){
									//Do nothing
								}else{
									xk=(int)((x[i][k]-xmin)*xscale);
									yk=(int)((y[i][k]-ymin)*yscale);



									g2.drawLine(xprev+xoffset+x1,
											-yprev+y2-yoffset,
											xk+xoffset+x1,
											-yk+y2-yoffset);
									g2.fillOval(x1+xoffset+xk-hpsize,
											y2-yk-hpsize-yoffset,
											psize,psize);

								}
							}
						}
					}
					break;

				case 3:                  // If dashed line plot

					float[] dash = {3.0f, 4.0f};
					g2.setStroke(new BasicStroke(1.0f, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND, 1.0f, dash, 0.0f));

					xk=(int)((x[i][0]-xmin)*xscale);
					yk=(int)((y[i][0]-ymin)*yscale);
					for(k=0; k<npoints[i]; k++) {

						xprev=xk;
						yprev=yk;

						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){  

							xk=(int)((x[i][k]-xmin)*xscale);
							yk=(int)((y[i][k]-ymin)*yscale);

						}else{
							go = true;
							if(!first){
								xk=(int)((x[i][k]-xmin)*xscale);
								yk=(int)((y[i][k]-ymin)*yscale);
								first = true;
							}else{
								if( xprev < 0 || yprev < 0 ){
									//Do nothing
								}else{
									xk=(int)((x[i][k]-xmin)*xscale);
									yk=(int)((y[i][k]-ymin)*yscale);



									g2.drawLine(xprev+xoffset+x1,
											-yprev+y2-yoffset,
											xk+xoffset+x1,
											-yk+y2-yoffset);
								}
							}
						}
					}
					break;

				case 4:                 //  If open circle plot
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.drawOval(x1+xoffset+xk-hpsize,
								y2-yk-hpsize-yoffset,
								psize,psize);
					}
					break;

				case 5:                 //  If solid circle plot
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.fillOval(x1+xoffset+xk-hpsize,
								y2-yk-hpsize-yoffset,
								psize,psize);
					}
					break;

				case 6:                 // If filled square plot
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.fillRect(x1+xoffset+xk-hpsize,
								y2-yk-hpsize-yoffset,
								psize,psize);
					}
					break;

				case 7:                 // If open square plot
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.drawRect(x1+xoffset+xk-hpsize,
								y2-yk-hpsize-yoffset,
								psize,psize);
					}
					break;

					// Following is poor man's dashed line.  It
					// leaves equal blank intervals in the x
					// coordinate, not in the local length of the
					// line segement.

				case 8:                 // x-symbol plot
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.drawLine(x1+xoffset+xk-hpsize,
								y2-yk-hpsize-yoffset,
								x1+xoffset+xk-hpsize+psize,
								y2-yk-hpsize-yoffset+psize);
						g2.drawLine(x1+xoffset+xk-hpsize,
								y2-yk-hpsize-yoffset+psize,
								x1+xoffset+xk-hpsize+psize,
								y2-yk-hpsize-yoffset);
					}
					break;

				case 9:                 // x-symbol plot + square
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.drawRect(x1+xoffset+xk-hpsize,
								y2-yk-hpsize-yoffset,
								psize,psize);
						g2.drawLine(x1+xoffset+xk-hpsize,
								y2-yk-hpsize-yoffset,
								x1+xoffset+xk-hpsize+psize,
								y2-yk-hpsize-yoffset+psize);
						g2.drawLine(x1+xoffset+xk-hpsize,
								y2-yk-hpsize-yoffset+psize,
								x1+xoffset+xk-hpsize+psize,
								y2-yk-hpsize-yoffset);
					}
					break;

				case 10:                 // + symbol plot
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.drawLine(x1+xoffset+xk-hpsize,
								y2-yk-yoffset,
								x1+xoffset+xk-hpsize+psize,
								y2-yk-yoffset);
						g2.drawLine(x1+xoffset+xk,
								y2-yk-hpsize-yoffset,
								x1+xoffset+xk,
								y2-yk-hpsize-yoffset+psize);
					}
					break;

				case 11:                 // + symbol plot + square
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.drawRect(x1+xoffset+xk-hpsize,
								y2-yk-hpsize-yoffset,
								psize,psize);
						g2.drawLine(x1+xoffset+xk-hpsize,
								y2-yk-yoffset,
								x1+xoffset+xk-hpsize+psize,
								y2-yk-yoffset);
						g2.drawLine(x1+xoffset+xk,
								y2-yk-hpsize-yoffset,
								x1+xoffset+xk,
								y2-yk-hpsize-yoffset+psize);
					}
					break;

				case 12:                 // Open diamonds
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.drawLine(x1+xoffset+xk,
								y2-yk-yoffset-hpsize,
								x1+xoffset+xk+hpsize,
								y2-yk-yoffset);
						g2.drawLine(x1+xoffset+xk+hpsize,
								y2-yk-yoffset,
								x1+xoffset+xk,
								y2-yk+hpsize-yoffset);
						g2.drawLine(x1+xoffset+xk,
								y2-yk-yoffset-hpsize,
								x1+xoffset+xk-hpsize,
								y2-yk-yoffset);
						g2.drawLine(x1+xoffset+xk-hpsize,
								y2-yk-yoffset,
								x1+xoffset+xk,
								y2-yk+hpsize-yoffset);
					}
					break;

				case 13:                 // Open down triangles
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.drawLine(x1+xoffset+xk-hpsize,
								y2-yk-yoffset-hpsize,
								x1+xoffset+xk+hpsize,
								y2-yk-yoffset-hpsize);
						g2.drawLine(x1+xoffset+xk-hpsize,
								y2-yk-yoffset-hpsize,
								x1+xoffset+xk,
								y2-yk-yoffset+hpsize);
						g2.drawLine(x1+xoffset+xk+hpsize,
								y2-yk-yoffset-hpsize,
								x1+xoffset+xk,
								y2-yk-yoffset+hpsize);
					}
					break;

				case 14:                 // Open up triangles
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.drawLine(x1+xoffset+xk,
								y2-yk-yoffset-hpsize,
								x1+xoffset+xk-hpsize,
								y2-yk-yoffset+hpsize);
						g2.drawLine(x1+xoffset+xk-hpsize,
								y2-yk-yoffset+hpsize,
								x1+xoffset+xk+hpsize,
								y2-yk-yoffset+hpsize);
						g2.drawLine(x1+xoffset+xk,
								y2-yk-yoffset-hpsize,
								x1+xoffset+xk+hpsize,
								y2-yk-yoffset+hpsize);
					}
					break;

				case 15:  //  Horizontal open oval (use 5 or greater dotSize)
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.drawOval(x1+xoffset+xk-hpsize,
								y2-yk-hpsize/2-yoffset,
								psize,psize/2);
					}
					break;

				case 16:  //  Horizontal filled oval (use 5 or greater dotSize)
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.fillOval(x1+xoffset+xk-hpsize,
								y2-yk-hpsize/2-yoffset,
								psize,psize/2);
					}
					break;

				case 17:  //  vertical open oval (use 5 or greater dotSize)
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.drawOval(x1+xoffset+xk-hpsize/2,
								y2-yk-hpsize-yoffset,
								psize/2,psize);
					}
					break;

				case 18:  //  vertical filled oval (use 5 or greater dotSize)
					for(k=0; k<npoints[i]; k++){
						// Don't plot if out of bounds
						if(x[i][k] < xmin  ||
								x[i][k] > xmax  ||
								y[i][k] < ymin  ||
								y[i][k] > ymax){continue;}
						xk=(int)((x[i][k]-xmin)*xscale);
						yk=(int)((y[i][k]-ymin)*yscale);
						g2.fillOval(x1+xoffset+xk-hpsize/2,
								y2-yk-hpsize-yoffset,
								psize/2,psize);
					}
					break;

				}
			}
		}


		// draw plot legend with box offset by xlegoff and ylegoff
		// from the upper left corner of plot box (which is offset
		// itself by x1 and x2 from the upper left applet corner).
		// Only the curves actually plotted (for which doplot[i] = 1)
		// are included in the legend.

		if(!showLegend){return;}  // Display legend only if
		// showLegend is true

		g2.setFont(smallFont);
		g2.setStroke(new BasicStroke(1));

		// find width of longest legend string & add 25.

		int howMany = 0;    // Number of curves for which doplot = 1
		int widleg=smallFontMetrics.stringWidth(curvetitle[0]);

		for (i=0; i<imax; i++){
			if (doplot[i] == 1) {
				int widtest=smallFontMetrics.stringWidth(curvetitle[i]);
				if(widtest > widleg){
					widleg=widtest;
				}
				howMany ++;
			}
		}
		widleg+=25;

		int bls=smallFontMetrics.getAscent()+ 2;
		int hgtleg=(howMany)*bls;
		g2.setColor(dropShadow);
		g2.fillRect(x1+xlegoff+2,         // drop shadow
				y1+ylegoff+2,
				widleg+5,
				hgtleg+5);
		g2.setColor(legendfg);
		g2.fillRect(x1+xlegoff,           // legend box fill
				y1+ylegoff,
				widleg+5,
				hgtleg+5);
		g2.setColor(legendbg);
		g2.drawRect(x1+xlegoff,           // legend box outline
				y1+ylegoff,
				widleg+5,
				hgtleg+5);
		howMany = 0;
		int s=1;

		colorIndex = 0;

		for(i=0; i <imax; i++){          // legends

			if( doplot[i] == 1){

				colorIndex = i;

				/*if(i>=40){

               	  	colorIndex=i-40;

               	  }*/

				g2.setColor(lcolor[colorIndex]);
				g2.drawString(curvetitle[i],x1+xlegoff+25,
						y1+12+ylegoff+bls*howMany);

				switch(mode[i]){

				case 1:
					g2.drawLine(x1+xlegoff+5,y1+ylegoff +12 - bls/2 + bls*howMany + s,
							x1+xlegoff+21,y1+12+ylegoff - bls/2 + bls*howMany + s);
					break;

				case 2:
					g2.drawLine(x1+xlegoff+5,y1+ylegoff +12- bls/2 + bls*howMany + s,
							x1+xlegoff+21,y1+ylegoff +12 - bls/2 + bls*howMany + s);
					g2.fillOval(x1+xlegoff+13-hpsize,
							y1+12+ylegoff-bls/2+bls*howMany-hpsize+s,psize,psize);
					break;

				case 3:
					g2.drawLine(x1+xlegoff+6,y1+ylegoff +12 - bls/2 +bls*howMany + s,
							x1+xlegoff+10,y1+12+ylegoff - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+16,y1+ylegoff +12 - bls/2 +bls*howMany + s,
							x1+xlegoff+20,y1+12+ylegoff - bls/2 + bls*howMany + s);
					break;

				case 4:
					g2.drawOval(x1+xlegoff+7,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize,psize,psize);
					/*g2.drawOval(x1+xlegoff+17,
                                   y1+ylegoff+12-bls/2+bls*howMany+s-hpsize,psize,psize);*/
                                   break;

				case 5:
					g2.fillOval(x1+xlegoff+7,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize,psize,psize);
					g2.fillOval(x1+xlegoff+17,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize,psize,psize);
					break;

				case 6:
					g2.fillRect(x1+xlegoff+7,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize,psize,psize);
					g2.fillRect(x1+xlegoff+17,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize,psize,psize);
					break;

				case 7:
					g2.drawRect(x1+xlegoff+7,
							y1+ylegoff+12-bls/2+bls*howMany-hpsize+s,psize,psize);
					g2.drawRect(x1+xlegoff+17,
							y1+ylegoff+12-bls/2+bls*howMany-hpsize+s,psize,psize);
					break;

				case 8:
					g2.drawLine(x1+xlegoff+7-hpsize,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+7-hpsize+psize,
							y1+12+ylegoff -hpsize+psize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+7-hpsize,
							y1+ylegoff +12 -hpsize +psize - bls/2 +bls*howMany + s,
							x1+xlegoff+7-hpsize+psize,
							y1+12+ylegoff -hpsize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17-hpsize,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+17-hpsize+psize,
							y1+12+ylegoff -hpsize+psize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17-hpsize,
							y1+ylegoff +12 -hpsize +psize - bls/2 +bls*howMany + s,
							x1+xlegoff+17-hpsize+psize,
							y1+12+ylegoff -hpsize - bls/2 + bls*howMany + s);

					break;

				case 9:

					g2.drawRect(x1+xlegoff+7-hpsize,
							y1+ylegoff+12 -hpsize - bls/2 + bls*howMany + s,
							psize, psize);
					g2.drawRect(x1+xlegoff+17-hpsize,
							y1+ylegoff+12 -hpsize - bls/2 + bls*howMany + s,
							psize, psize);
					g2.drawLine(x1+xlegoff+7-hpsize,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+7-hpsize+psize,
							y1+12+ylegoff -hpsize+psize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+7-hpsize,
							y1+ylegoff +12 -hpsize +psize - bls/2 +bls*howMany + s,
							x1+xlegoff+7-hpsize+psize,
							y1+12+ylegoff -hpsize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17-hpsize,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+17-hpsize+psize,
							y1+12+ylegoff -hpsize+psize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17-hpsize,
							y1+ylegoff +12 -hpsize +psize - bls/2 +bls*howMany + s,
							x1+xlegoff+17-hpsize+psize,
							y1+12+ylegoff -hpsize - bls/2 + bls*howMany +s);

					break;

				case 10:

					g2.drawLine(x1+xlegoff+7-hpsize,
							y1+ylegoff +12 - bls/2 +bls*howMany + s,
							x1+xlegoff+7-hpsize+psize,
							y1+12+ylegoff - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+7,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+7,
							y1+12+ylegoff -hpsize +psize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17-hpsize,
							y1+ylegoff +12 - bls/2 +bls*howMany + s,
							x1+xlegoff+17-hpsize+psize,
							y1+12+ylegoff - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+17,
							y1+12+ylegoff -hpsize +psize - bls/2 + bls*howMany + s);

					break;

				case 11:

					g2.drawRect(x1+xlegoff+7-hpsize,
							y1+ylegoff+12 -hpsize - bls/2 + bls*howMany + s,
							psize, psize);
					g2.drawRect(x1+xlegoff+17-hpsize,
							y1+ylegoff+12 -hpsize - bls/2 + bls*howMany + s,
							psize, psize);
					g2.drawLine(x1+xlegoff+7-hpsize,
							y1+ylegoff +12 - bls/2 +bls*howMany + s,
							x1+xlegoff+7-hpsize+psize,
							y1+12+ylegoff - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+7,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+7,
							y1+12+ylegoff -hpsize +psize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17-hpsize,
							y1+ylegoff +12 - bls/2 +bls*howMany + s,
							x1+xlegoff+17-hpsize+psize,
							y1+12+ylegoff - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+17,
							y1+12+ylegoff -hpsize +psize - bls/2 + bls*howMany + s);

					break;

				case 12:

					g2.drawLine(x1+xlegoff+7,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+7+hpsize,
							y1+12+ylegoff - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+7+hpsize,
							y1+ylegoff +12 - bls/2 +bls*howMany + s,
							x1+xlegoff+7,
							y1+12+ylegoff +hpsize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+7,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+7-hpsize,
							y1+12+ylegoff - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+7-hpsize,
							y1+ylegoff +12 - bls/2 +bls*howMany + s,
							x1+xlegoff+7,
							y1+12+ylegoff +hpsize - bls/2 + bls*howMany + s);

					g2.drawLine(x1+xlegoff+17,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+17+hpsize,
							y1+12+ylegoff - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17+hpsize,
							y1+ylegoff +12 - bls/2 +bls*howMany + s,
							x1+xlegoff+17,
							y1+12+ylegoff +hpsize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+17-hpsize,
							y1+12+ylegoff - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17-hpsize,
							y1+ylegoff +12 - bls/2 +bls*howMany + s,
							x1+xlegoff+17,
							y1+12+ylegoff +hpsize - bls/2 + bls*howMany + s);

					break;

				case 13:

					g2.drawLine(x1+xlegoff+7-hpsize,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+7+hpsize,
							y1+12+ylegoff -hpsize -bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+7-hpsize,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+7,
							y1+12+ylegoff +hpsize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+7 +hpsize,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+7,
							y1+12+ylegoff +hpsize - bls/2 + bls*howMany + s);

					g2.drawLine(x1+xlegoff+17-hpsize,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+17+hpsize,
							y1+12+ylegoff -hpsize -bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17-hpsize,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+17,
							y1+12+ylegoff +hpsize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17 +hpsize,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+17,
							y1+12+ylegoff +hpsize - bls/2 + bls*howMany + s);

					break;

				case 14:

					g2.drawLine(x1+xlegoff+7,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+7-hpsize,
							y1+12+ylegoff +hpsize -bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+7-hpsize,
							y1+ylegoff +12 +hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+7+hpsize,
							y1+12+ylegoff +hpsize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+7,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+7+hpsize,
							y1+12+ylegoff +hpsize - bls/2 + bls*howMany + s);

					g2.drawLine(x1+xlegoff+17,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+17-hpsize,
							y1+12+ylegoff +hpsize -bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17-hpsize,
							y1+ylegoff +12 +hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+17+hpsize,
							y1+12+ylegoff +hpsize - bls/2 + bls*howMany + s);
					g2.drawLine(x1+xlegoff+17,
							y1+ylegoff +12 -hpsize - bls/2 +bls*howMany + s,
							x1+xlegoff+17+hpsize,
							y1+12+ylegoff +hpsize - bls/2 + bls*howMany + s);

					break;

				case 15:

					g2.drawOval(x1+xlegoff+7-hpsize,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize/2,
							psize,psize/2);

					g2.drawOval(x1+xlegoff+17-hpsize,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize/2,
							psize,psize/2);

					break;

				case 16:

					g2.fillOval(x1+xlegoff+7-hpsize,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize/2,
							psize,psize/2);

					g2.fillOval(x1+xlegoff+17-hpsize,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize/2,
							psize,psize/2);

					break;

				case 17:

					g2.drawOval(x1+xlegoff+7-hpsize/2,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize,
							psize/2,psize);

					g2.drawOval(x1+xlegoff+17-hpsize/2,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize,
							psize/2,psize);

					break;

				case 18:

					g2.fillOval(x1+xlegoff+7-hpsize/2,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize,
							psize/2,psize);

					g2.fillOval(x1+xlegoff+17-hpsize/2,
							y1+ylegoff+12-bls/2+bls*howMany+s-hpsize,
							psize/2,psize);

					break;

				}

				howMany++;
			}

		}

	}

	// ---------------------------------------------------------------------------
	//  Method rightSuperScript to position precisely a right superscript
	//  on a string in graphics mode.  ARGUMENTS:
	//     String s - The string to which the right superscript will be added
	//     String ss - The superscript to be added
	//     int x - The x coordinate in pixels for the main string
	//     int y - The y coordinate in pixels for the main string
	//     Font f - The font currently in use.  See most recent setFont(),
	//              or use getFont() method of Font object
	//     String relscale - Takes values "small", "medium", and "large"
	//                       and sets relative size of superscript relative
	//                       to main string.  These make the size of the
	//                       superscript 5,4, and 3 points smaller than
	//                       main string.  Default is "medium" (4 points smaller)
	//     Graphics g2 - The graphics object from which this method is being
	//                  called.  Typically set in something like the argument
	//                  of a paint method:
	//                       public void paint(Graphics g2){
	//                          statements of method paint
	//                       }
	//                  from which this method is being called.
	//
	//     USAGE:
	//         GraphicsGoodies2 gg=new GraphicsGoodies2();  //Instantiate this class
	//         int leng=gg.rightSuperScript(s,ss,x,y,f,relscale,g2);
	//
	//     The value leng returned is the length in pixels of the string with
	//     superscript appended.  This is useful for concatenation of further
	//     strings on the original string plus subscript.  Here is an example
	//     of typesetting a string with multiple superscripts that uses the
	//     returned string length to position subsequent portions of the string:
	//
	//  GraphicsGoodies2 gg=new GraphicsGoodies2();
	//  int len=0;
	//  len+=gg.rightSuperScript("M","1",xline,yline,font18,"medium",g2);
	//  len+=gg.rightSuperScript("d","1",xline+len,yline,font18,"medium",g2);
	//  len+=gg.rightSuperScript(" = M","2",xline+len,yline,font18,"medium",g2);
	//  len+=gg.rightSuperScript("d","2",xline+len,yline,font18,"medium",g2);


	// ---------------------------------------------------------------------------

	/**
	 * Right super script.
	 *
	 * @param s the s
	 * @param ss the ss
	 * @param x the x
	 * @param y the y
	 * @param f the f
	 * @param relscale the relscale
	 * @param g the g
	 * @return the int
	 */
	public int rightSuperScript(String s,String ss,int x,int y,Font f,
			String relscale, Graphics g){

		FontMetrics stringFontMetrics=getFontMetrics(f);
		g.setFont(f);  // Get the info on the main string font
		int fsize=f.getSize();
		String fname=f.getName();
		int style=f.getStyle();
		if (style==2){style=0;}  // Don't allow a superscript to be italic
		if (style==3){style=1;}  // or bold italic (not good style).
		int sizedecrease=4;      // Set size offset of superscript
		if (relscale=="small"){sizedecrease=5;}
		if (relscale=="large"){sizedecrease=3;}
		Font superf=new Font(fname, style, fsize-sizedecrease); // ss font
		FontMetrics superfFontMetrics=getFontMetrics(superf);
		int rightshift=stringFontMetrics.stringWidth(s);   // ss positioning
		int upshift=stringFontMetrics.getAscent();
		g.drawString(s,x,y);   //  Draw main string
		g.setFont(superf);
		int superwidth=superfFontMetrics.stringWidth(ss);
		g.drawString(ss,x+rightshift+1,y-upshift/3);  //  Draw superscript
		g.setFont(f);    // Reset font to original
		return rightshift+superwidth+1;  // Return full width of the
		// string + superscript, to
		// help in positioning subsequent
		// strings.
	}



	// ---------------------------------------------------------------------------
	//  Method rightSubScript to position precisely a right subscript
	//  on a string in graphics mode.  ARGUMENTS:
	//     String s - The string to which the right subscript will be added
	//     String ss - The superscript to be added
	//     int x - The x coordinate in pixels for the main string
	//     int y - The y coordinate in pixels for the main string
	//     Font f - The font currently in use.  See most recent setFont(),
	//              or use getFont() method of Font object
	//     String relscale - Takes values "small", "medium", and "large"
	//                       and sets relative size of superscript relative
	//                       to main string.  These make the size of the
	//                       superscript 5,4, and 3 points smaller than
	//                       main string.  Default is "medium" (4 points smaller)
	//     Graphics g - The graphics object from which this method is being
	//                  called.  Typically set in something like the argument
	//                  of a paint method:
	//                       public void paint(Graphics g){
	//                          statements of method paint
	//                       }
	//                  from which this method is being called.
	//
	//     USAGE:
	//         GraphicsGoodies2 gg=new GraphicsGoodies2();  //Instantiate this class
	//         int leng=gg.rightSubScript(s,ss,x,y,f,relscale,g);
	//
	//     The value leng returned is the length in pixels of the string with
	//     superscript appended.  This is useful for concatenation of further
	//     strings on the original string plus subscript. Here is an example
	//     of typesetting a string with multiple subscripts that uses the
	//     returned string length to position subsequent portions of the string:
	//
	//  GraphicsGoodies2 gg=new GraphicsGoodies2();
	//  int len=0;
	//  len+=gg.rightSubScript("M","1",xline,yline,font18,"medium",g);
	//  len+=gg.rightSubScript("d","1",xline+len,yline,font18,"medium",g);
	//  len+=gg.rightSubScript(" = M","2",xline+len,yline,font18,"medium",g);
	//  len+=gg.rightSubScript("d","2",xline+len,yline,font18,"medium",g);
	//
	// ---------------------------------------------------------------------------

	/**
	 * Right sub script.
	 *
	 * @param s the s
	 * @param ss the ss
	 * @param x the x
	 * @param y the y
	 * @param f the f
	 * @param relscale the relscale
	 * @param g the g
	 * @return the int
	 */
	public int rightSubScript(String s,String ss,int x,int y,Font f,
			String relscale, Graphics g){
		FontMetrics stringFontMetrics=getFontMetrics(f);
		g.setFont(f);  // Get the info on the main string font
		int fsize=f.getSize();
		String fname=f.getName();
		int style=f.getStyle();
		if (style==2){style=0;}  // Don't allow a subscript to be italic
		if (style==3){style=1;}  // or bold italic (not good style).
		int sizedecrease=4;      // Set size offset of superscript
		if (relscale=="small"){sizedecrease=5;}
		if (relscale=="large"){sizedecrease=3;}
		Font superf=new Font(fname, style, fsize-sizedecrease); // ss font
		FontMetrics superfFontMetrics=getFontMetrics(superf);
		int rightshift=stringFontMetrics.stringWidth(s);   // ss positioning
		int upshift=stringFontMetrics.getAscent();
		g.drawString(s,x,y);   //  Draw main string
		g.setFont(superf);
		int superwidth=superfFontMetrics.stringWidth(ss);
		g.drawString(ss,x+rightshift+1,y+upshift/3);  //  Draw superscript
		g.setFont(f);    // Reset font to original
		return rightshift+superwidth+1;  // Return full width of the
		// string + superscript, to
		// help in positioning subsequent
		// strings.
	}



	// ---------------------------------------------------------------------------
	//  Method decimalPlace returns string  representation of double
	//  with a fixed number of places after the decimal.  The number of places
	//  after the decimal is given by integer "nright" (>=0) and the double is
	//  passed as the variable "number".  Routine handles both decimal and
	//  scientific (E) notation.  Rounds floating point style (e.g., 5.676
	//  truncated to 2 decimal places returns 5.68, not 5.67).  Pads the right
	//  with zeros if insufficient digits after the decimal (e.g., a request
	//  to truncate 5.67 to 4 decimal places returns 5.6700).  If nright=0, no
	//  decimal is shown (e.g., 3 instead of 3.).
	//
	//  EXAMPLE OF USING FROM ANOTHER CLASS:
	//       GraphicsGoodies2 gg=new GraphicsGoodies2();  // Instantiate this class
	//       String nstring = gg.decimalPlace(nright,number);
	//       gg.drawString("Variable=" + decimalPlace(3,variable),100,200);
	//
	// ---------------------------------------------------------------------------


	/**
	 * Decimal place.
	 *
	 * @param nright the nright
	 * @param number the number
	 * @return the string
	 */
	public String decimalPlace(int nright, double number) {
		double n=number;
		String tleft;         // Mantissa left of .
		String tright;        // Original mantissa right of .
		String tright2="";    // Final mantissa right of .
		String eleft="";
		String eright="";

		String total;
		total=String.valueOf(n);
		int temp1=0;
		int temp2=0;
		int i=1;
		int dotil=0;
		int nperiod=0;

		//  Check for scientific notation
		int ne=total.indexOf("E");
		if(ne > -1){
			eleft=total.substring(0,ne);
			eright=total.substring(ne);  //  string containing exponent
			total=eleft;   // string containing mantissa
		}

		//  Roundoff to proper number of places.  Last digit retained
		//  bumped up by one if the first one cut off is 5 or greater.
		Double mydouble=Double.valueOf(total);  // 2 steps to convert
		double nn=mydouble.doubleValue();       // string to double
		double nnn=Math.round(nn*Math.pow(10,nright));
		total=String.valueOf(nnn/Math.pow(10,nright));

		//  Split mantissa left of the decimal place;
		//  return if no decimal or no places to right of decimal
		nperiod=total.indexOf(".");
		if(nperiod == 0 || nperiod == -1){return total+eright;}
		tleft=total.substring(0,nperiod); // mantissa left of decimal
		tright=total.substring(nperiod);  // original mantissa right of .
		// including decimal

		//  Pad tright with zeros if necessary to bring up
		//  to the desired number of places to right of decimal
		if(tright.length()-1 <= nright){
			dotil=nright-tright.length();
			for (i=0; i<= dotil+1; i++){
				tright=tright+"0";
			}
		}

		//  truncate the mantissa to right of decimal to nright places
		temp1=0;
		temp2=nright+1;
		if(tright.length() > nright) {
			try{tright2=tright.substring(temp1,temp2);}
			catch (StringIndexOutOfBoundsException e)
			{ ; }
		}
		else {
			tright2=tright;
		}
		// If number of decimal places is zero, strip off any decimal
		// (e.g., return 3 instead of 3.)
		if (nright == 0){
			tright2 = tright2.substring(1,tright2.length());
		}
		//  Return the truncated string
		return tleft+tright2+eright;
	}


	// ---------------------------------------------------------------------------
	//  Method drawVector to draw a vector in graphics mode.  Method is overloaded
	//  (two versions of it).  This is the cartesian argument method.  The next
	//  method below defines the polar coordinate method.  Java decides which to
	//  use by examining the data types of the call arguments.
	//  ARGUMENTS FOR THIS (CARTESIAN) METHOD:
	//     int x1 - The x coordinate in pixels for the beginning of vector
	//     int y1 - The y coordinate in pixels for the beginning of vector
	//     int x2 - The x coordinate in pixels for the arrow tip of vector
	//     int y2 - The y coordinate in pixels for the arrow tip of vector
	//     Graphics g - The graphics object from which this method is being
	//                  called.  Typically set in something like the argument
	//                  of a paint method:
	//                       public void paint(Graphics g){
	//                          statements of method paint
	//                       }
	//                  from which this method is being called.
	//
	//   USAGE:
	//         GraphicsGoodies2 gg=new GraphicsGoodies2(); // Instantiate this class
	//         gg.drawVector(x1,y1,x2,y2,g);               // Access the method
	//
	// ---------------------------------------------------------------------------

	// cartesian version of the method
	/**
	 * Draw vector.
	 *
	 * @param x1 the x1
	 * @param y1 the y1
	 * @param x2 the x2
	 * @param y2 the y2
	 * @param g the g
	 */
	public void drawVector(int x1,int y1,int x2,int y2,Graphics g) {
		int fac=1;
		double theta=0.38;  // angle for shape of arrowhead
		double sintheta=Math.sin(theta);
		double dely=(y2-y1);
		double delx=(x2-x1);
		double phi=0.0;

		if(Math.abs(delx) <= 1.0e-10){
			phi=1.5708;         // handle exactly vertical line
		}
		else{
			phi=Math.atan(dely/delx);
		}
		double a=4;  // Sets arrowhead halfwidth in pixels
		if(x2 < x1){fac=-1;}  // For upper left and lower left quadrants
		int delxR=fac*(int)(a*Math.cos(phi-theta)/sintheta);
		int delyR=fac*(int)(a*Math.sin(phi-theta)/sintheta);
		int delxL=fac*(int)(a*Math.cos(phi+theta)/sintheta);
		int delyL=fac*(int)(a*Math.sin(phi+theta)/sintheta);
		int[] xharrow={x2,x2-delxL,x2-delxR};
		int[] yharrow={y2,y2-delyL,y2-delyR};
		g.drawLine(x1,y1,x2,y2);
		g.fillPolygon(xharrow,yharrow,3);
	}


	// ---------------------------------------------------------------------------
	//  Method drawVector to draw a vector in graphics mode.  Method is overloaded
	//  (two versions of it).  This is the polar coordinate method.  The preceding
	//  method above defines the cartesian method.  Java decides which to
	//  use by examining the data types of the call arguments.
	//  ARGUMENTS FOR THIS (POLAR) METHOD:
	//     int x1 - The x coordinate in pixels for the beginning of vector
	//     int y1 - The y coordinate in pixels for the beginning of vector
	//     int r - The length in pixels for the vector
	//     double phi - The angle in degrees for the orientation of the vector.
	//                  Uses the Java angle convention:  Zero degrees at
	//                  the 3 o'clock position and angles measured counterclockwise.
	//                  Thus, for a vector straight up phi=90 degrees and for
	//                  one straight down phi= -90 degrees.
	//     Graphics g - The graphics object from which this method is being
	//                  called.  Typically set in something like the argument
	//                  of a paint method:
	//                       public void paint(Graphics g){
	//                          statements of method paint
	//                       }
	//                  from which this method is being called.
	//
	//   USAGE:
	//         GraphicsGoodies2 gg=new GraphicsGoodies2(); // Instantiate this class
	//         gg.drawVector(x1,y1,r,phi,g);               // Access the method
	//
	// ---------------------------------------------------------------------------

	// the polar coordinate method
	/**
	 * Draw vector.
	 *
	 * @param x1 the x1
	 * @param y1 the y1
	 * @param r the r
	 * @param phi the phi
	 * @param g the g
	 */
	public void drawVector(int x1,int y1,int r,double phi,Graphics g) {
		phi=-phi/57.2; // Convert to radians & insert minus sign to account
		// for java phase convention:  angles measured
		// counterclockwise from the 3 o'clock position.
		double delx=Math.cos(phi)*r;
		double dely=Math.sin(phi)*r;
		int x2=x1+(int)delx;
		int y2=y1+(int)dely;
		this.drawVector(x1,y1,x2,y2,g); // Invoke the other (cartesian) method

	}

	// ----------------------------------------------------------------------------------
	//  Method drawDashedLine draws a dashed line in a graphics environment.  Method is
	//  overloaded (two versions of it).  This one allows the length of the dash and the
	//  blank to be specified through deldash and delblank.  The other does not take these
	//  arguments and uses defaults for them.  Arguments have similar explanation as
	//  for drawVector above.
	// ----------------------------------------------------------------------------------

	/**
	 * Draw dashed line.
	 *
	 * @param x1 the x1
	 * @param y1 the y1
	 * @param x2 the x2
	 * @param y2 the y2
	 * @param deldash the deldash
	 * @param delblank the delblank
	 * @param g the g
	 */
	public void drawDashedLine(int x1,int y1,int x2,int y2,int deldash,
			int delblank,Graphics g) {
		double delx=(double)(x2-x1);
		double dely=(double)(y2-y1);
		double phi;
		if(Math.abs(delx) <= 1.0e-10){    //  Handle the vertical line case
			phi=1.5708;
		} else {
			phi=Math.atan(dely/delx);
		}
		double cosphi=Math.cos(phi);
		double sinphi=Math.sin(phi);
		double h;
		if(Math.abs(sinphi) <= 1.0e-10){  //  Handle the horizontal line case
			h=delx;
		} else {
			h=dely/sinphi;
		}
		int dashnumber=(int)(h/(double)(deldash+delblank)+0.5);
		double delxdash=(double)deldash*cosphi;
		double delydash=(double)deldash*sinphi;
		double delxblank=(double)delblank*cosphi;
		double delyblank=(double)delblank*sinphi;
		double oldx=(double)x1;
		double oldy=(double)y1;
		double newx=(double)x1+delxdash;
		double newy=(double)y1+delydash;
		for (int i = 1; i <= dashnumber; i++){
			g.drawLine((int)oldx,(int)oldy,(int)newx,(int)newy);
			oldx+=delxdash+delxblank;
			oldy+=delydash+delyblank;
			newx=oldx+delxdash;
			newy=oldy+delydash;
		}
	}

	//  Overloaded version that does not expect the length of the dash and blanks
	//  to be specified by user.  See further explanation above.
	/**
	 * Draw dashed line.
	 *
	 * @param x1 the x1
	 * @param y1 the y1
	 * @param x2 the x2
	 * @param y2 the y2
	 * @param g the g
	 */
	public void drawDashedLine(int x1,int y1,int x2,int y2,Graphics g) {
		int deldash=4;
		int delblank=4;
		this.drawDashedLine(x1,y1,x2,y2,deldash,delblank,g);
	}

	// ---------------------------------------------------------------------------------
	//  Method drawDottedLine draws a dotted line between the specified endpoints.  See
	//  the discussion of the method drawVector above for the arguments.
	// ---------------------------------------------------------------------------------


	/**
	 * Draw dotted line.
	 *
	 * @param x1 the x1
	 * @param y1 the y1
	 * @param x2 the x2
	 * @param y2 the y2
	 * @param g the g
	 */
	public void drawDottedLine(int x1,int y1,int x2,int y2,Graphics g) {
		int deldash=1;
		int delblank=3;
		this.drawDashedLine(x1,y1,x2,y2,deldash,delblank,g);
	}


	/**
	 * Left super script.
	 *
	 * @param s the s
	 * @param ss the ss
	 * @param x the x
	 * @param y the y
	 * @param f the f
	 * @param relscale the relscale
	 * @param g the g
	 * @return the int
	 */
	public int leftSuperScript(String s,String ss,int x,int y,Font f,
			String relscale, Graphics g){

		FontMetrics stringFontMetrics=getFontMetrics(f);

		g.setFont(f);  // Get the info on the main string font

		int fsize=f.getSize();

		String fname=f.getName();

		int style=f.getStyle();

		if (style==2){style=0;}  // Don't allow a superscript to be italic
		if (style==3){style=1;}  // or bold italic (not good style).
		int sizedecrease=4;      // Set size offset of superscript

		if (relscale=="small"){sizedecrease=5;}
		if (relscale=="large"){sizedecrease=3;}

		Font superf=new Font(fname, style, fsize-sizedecrease); // ss font

		FontMetrics superfFontMetrics=getFontMetrics(superf);

		int rightshift=superfFontMetrics.stringWidth(ss);   // ss positioning

		int upshift=stringFontMetrics.getAscent();

		g.setFont(superf);

		g.drawString(ss,x,y-upshift/3);   //  Draw main string

		g.setFont(f);

		int superwidth=stringFontMetrics.stringWidth(s);

		g.drawString(s,x+rightshift+1,y);  //  Draw superscript

		g.setFont(f);    // Reset font to original

		return rightshift+superwidth+1;  // Return full width of the
		// string + superscript, to
		// help in positioning subsequent
		// strings.
	}


}   // ----- end class GraphicsGoodies2 -----


